# https://cloud.google.com/appengine/docs/standard/python3/config/appref

# application: brid-gy
runtime: python37
# default_expiration: 1h

# https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices
# https://docs.gunicorn.org/en/latest/settings.html#timeout
entrypoint: gunicorn --workers 1 --threads 10 --timeout 60 -b :$PORT app:application

# background: https://github.com/snarfed/bridgy/issues/578
automatic_scaling:
  min_instances: 0
  # max_idle_instances: 1
  max_pending_latency: 100ms  # default is 30
  max_concurrent_requests: 12

handlers:

# static
- url: /(static/bootstrap.*\.css)
  static_files: oauth_dropins/\1
  upload: oauth_dropins/static/bootstrap.*\.css

- url: /static
  static_dir: static

- url: /.well-known
  static_dir: .well-known

- url: /static/style.css
  static_files: static/style.css
  upload: static/style.css

- url: /static/bridgy.js
  static_files: static/bridgy.js
  upload: static/bridgy.js

- url: /oauth_dropins/static
  static_dir: oauth_dropins/static

- url: /fonts
  static_dir: oauth_dropins/fonts

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# dynamic
- url: .*
  script: auto
  secure: always
