# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2.1

jobs:
  build:
    docker:
      # https://hub.docker.com/r/google/cloud-sdk
      - image: google/cloud-sdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - venv-npm-3-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "browser-extension/package.json" }}
            - venv-npm-3-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - venv-npm-3-{{ .Branch }}
            - venv-npm-3

      - run:
          name: Base dependencies
          command: |
            apt-get update
            apt-get install -y npm nodejs

      - run:
          name: Python dependencies
          command: |
            pip install -U pip
            pip -V
            pip install -U -r requirements.txt
            pip install coverage coveralls

      - run:
          name: JavaScript dependencies
          command: |
            cd browser-extension
            npm install

      - run:
          name: Python tests
          command: |
            CLOUDSDK_CORE_PROJECT=brid-gy gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0 --host-port=localhost:8089 < /dev/null >& /dev/null &
            sleep 5s
            python3 -m coverage run --source=. --omit=admin.py,appengine_config.py,local3/\*,logs.py,scripts/\*,tests/\* -m unittest discover -v
            if [ "$TWITTER_LIVE_TEST_APP_KEY" != "" ]; then PYTHONPATH=. python3 tests/twitter_live_test.py --debug; fi
            python3 -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then coveralls || true; fi

      - run:
          name: JavaScript tests
          command: |
            cd browser-extension
            npm run test

      - save_cache:
          key: venv-npm-3-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "browser-extension/package.json" }}
          paths:
            - "/usr/local/lib/python3.7/dist-packages/"
            - "browser-extension/node_modules"

      - store_artifacts:
          path: /tmp/coverage_html
