# CircleCI automatically reads this file from our repo and uses it for
# configuration. Docs:
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/sample-config/
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout

      - restore_cache:
          keys:
            - venv-npm-5-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "browser-extension/package.json" }}
            - venv-npm-5-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - venv-npm-5-{{ .Branch }}
            - venv-npm-5

      - run:
          name: Base dependencies
          command: |
            # Node
            curl -fsSL https://deb.nodesource.com/setup_current.x | sudo bash -
            # google-cloud-sdk: https://cloud.google.com/sdk/docs/install#deb
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update
            sudo apt-get install -y nodejs apt-transport-https ca-certificates gnupg google-cloud-sdk google-cloud-sdk-datastore-emulator default-jre

      - run:
          name: Python dependencies
          command: |
            pip install -U pip
            pip -V
            # make sure we install these at head, below
            pip uninstall -y granary oauth-dropins
            pip install -U -r requirements.txt
            pip install coverage coveralls

      - run:
          name: JavaScript dependencies
          command: |
            cd browser-extension
            npm install

      - run:
          name: Python tests
          command: |
            CLOUDSDK_CORE_PROJECT=brid-gy gcloud beta emulators datastore start --no-store-on-disk --consistency=1.0 --host-port=localhost:8089 < /dev/null >& /dev/null &
            sleep 5s
            python -m coverage run --source=. --omit=admin.py,appengine_config.py,logs.py,scripts/\*,tests/\* -m unittest discover -v
            if [ "$TWITTER_LIVE_TEST_APP_KEY" != "" ]; then PYTHONPATH=. python tests/twitter_live_test.py --debug; fi
            python -m coverage html -d /tmp/coverage_html
            if [ "$COVERALLS_REPO_TOKEN" != "" ]; then python -m coveralls || true; fi

      - run:
          name: JavaScript tests
          command: |
            cd browser-extension
            npm run test

      - save_cache:
          key: venv-npm-5-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "browser-extension/package.json" }}
          paths:
            - browser-extension/node_modules
            - /home/circleci/.pyenv
            # Ideally we'd cache these, but they need root, and the cimg/python
            # Docker image's default user is circleci :/
            # https://github.com/cypress-io/circleci-orb/issues/269
            #
            # - /usr/bin/node
            # - /usr/lib/google-cloud-sdk
            # - /usr/lib/jvm/java-11-openjdk-amd64

      - store_artifacts:
          path: /tmp/coverage_html
